---
title: "About"
---

We are a group of researchers working around the world and connected with our shared interest in microbiome research. 
The **Microbiome Network India** was conceptualized as a way to connect microbiome researchers of Indian origin and build a community that works towards:  

* Connecting with Indian microbiome experts.   
* Sharing our global expertise. 
* Fostering collaborations.  
* Creating awareness for microbiome research.   
* Organising talks and workshops.  

At present, the **Microbiome Network India** has 35 members from 8 time-zones (!) and at different stages of career.   

Interested?  
Join our slack workspace [microbiome-network-in](https://join.slack.com/t/microbiome-network-in/shared_invite/zt-skbpgrhs-C7REKkLMwUWSiypkRR_hfw)   

### Founder  

* Sudarshan A. Shetty ([info](https://microsud.github.io/sudarshanshetty.io/))   

### Core Team   
You?   

### Outreach Activities Team   
You?  

### Event Organising Team  
You?  

### Members  

* Aarthi Ravikrishnan ([info]())  
* Akshay Gaike ([info]())    
* Ankita Vaishampayan ([info]())   
* Anurup Mohanty ([info]())    
* Dattatray Mongad ([info](http://microdm.net.in/))   
* Dhiraj Dhotre ([info]())   
* Dhrati Patangia ([info]())   
* Divya N ([info]())    
* Gaurav Sharma ([info](https://sites.google.com/view/sharmaglab/))   
* Gayatree Mohapatra ([info]())      
* Himel Mallick ([info](http://www.himelmallick.org/))   
* Khemlal Nirmalkar ([info]())   
* Kunal Jani ([info]())   
* Mahendra jamdhade ([info]())   
* Mangesh Suryavanshi ([info]())   
* Namrata Iyer ([info]())   
* Nitin Bayal ([info]())   
* Praveen Rahi ([info](http://210.212.161.138/ncmr/details#drpraveen_rahiInfo))   
* Rahul Bodkhe ([info]())  
* Rajesh ([info]())  
* Rakeshkumar Yadav ([info]())  
* Ranjit ([info]())  
* Sai Suresh Hivarkar ([info]())  
* Sayed Irfan ([info]())  
* Shalaka Patil ([info]())  
* Shankar Manoharan ([info]())   
* Shashi Kiran ([info]())  
* Suryawanshi Padmaja ([info]())  
* Swapnil Kajale ([info]())  
* Swetha Sridhar ([info]())   
* Tanmay Dharmadhikari ([info]())  
* Tarini Ghosh ([info]())    
* Uday Pandey ([info]())  
* Vinay Rajput ([info]())   
* You?  

### Mentors/Advisors  
* You?  
