---
title: "Code of Conduct"
---

Code of Conduct for **Microbiome Network India**    
To be a truly great community, the Microbiome Network India welcomes people from all walks of life, with different backgrounds interested in microbiome research and with a wide range of experience. A diverse and friendly community will have more great ideas and more unique perspectives. We will work diligently to make the Microbiome Network India Slack community welcoming to everyone.  
The Microbiome Network India Slack Workspace Code of Conduct (v1)
As maintainers of this Slack channel, and in the interest of fostering an open and welcoming community, we pledge to respect all people who contribute.  
We are committed to making participation in this project a harassment-free experience for everyone, regardless of level of experience, gender, gender identity and expression, sexual orientation, disability, personal appearance, body size, race, ethnicity, age, religion, or nationality.  
Examples of unacceptable behaviour by participants include:  

* The use of sexualized language or imagery  
* Personal attacks  
* Trolling or insulting/derogatory comments  
* Public or private harassment  
* Publishing other's private information, such as physical or electronic addresses, without explicit permission  
* Caste and/or religion based remarks are unacceptable  
* Other unethical or unprofessional conduct  

The  Microbiome Network India reserves the right and responsibility to remove, edit, or reject any comments or other contributions that are not aligned with this Code of Conduct, or to ban temporarily or permanently any contributor for other behaviours that they deem inappropriate, threatening, offensive, or harmful.  
By adopting this Code of Conduct, the Microbiome Network India commit themselves to fairly and consistently applying these principles to every aspect of managing this community. Please note that private messages are considered the intellectual property of the sender.  
Reporting harassment - directly to admins - is the only acceptable reason to re-publish them. All complaints will be reviewed and investigated and will result in a response that is deemed necessary and appropriate to the circumstances. The Microbiome Network India is obligated to maintain confidentiality with regard to the reporter of an incident and is committed to promptly addressing any reported issues.  
We ask that you report concerns by sending an email to sudarshanshetty9@gmail.com  
Attribution  
This Code of Conduct is adapted from the Contributor Covenant, version 1.4, available at https://www.contributor-covenant.org/version/1/4/code-of-conduct.html   